In [1]:
import numpy as np
import pandas as pd

df_2015 = pd.read_csv("../original_data/2015.csv")

In [2]:
df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [3]:
df_2015['Country'].unique()

array(['Switzerland', 'Iceland', 'Denmark', 'Norway', 'Canada', 'Finland',
       'Netherlands', 'Sweden', 'New Zealand', 'Australia', 'Israel',
       'Costa Rica', 'Austria', 'Mexico', 'United States', 'Brazil',
       'Luxembourg', 'Ireland', 'Belgium', 'United Arab Emirates',
       'United Kingdom', 'Oman', 'Venezuela', 'Singapore', 'Panama',
       'Germany', 'Chile', 'Qatar', 'France', 'Argentina',
       'Czech Republic', 'Uruguay', 'Colombia', 'Thailand',
       'Saudi Arabia', 'Spain', 'Malta', 'Taiwan', 'Kuwait', 'Suriname',
       'Trinidad and Tobago', 'El Salvador', 'Guatemala', 'Uzbekistan',
       'Slovakia', 'Japan', 'South Korea', 'Ecuador', 'Bahrain', 'Italy',
       'Bolivia', 'Moldova', 'Paraguay', 'Kazakhstan', 'Slovenia',
       'Lithuania', 'Nicaragua', 'Peru', 'Belarus', 'Poland', 'Malaysia',
       'Croatia', 'Libya', 'Russia', 'Jamaica', 'North Cyprus', 'Cyprus',
       'Algeria', 'Kosovo', 'Turkmenistan', 'Mauritius', 'Hong Kong',
       'Estonia', 'Indonesia', 'Vietnam', 'Turkey', 'Kyrgyzstan',
       'Nigeria', 'Bhutan', 'Azerbaijan', 'Pakistan', 'Jordan',
       'Montenegro', 'China', 'Zambia', 'Romania', 'Serbia', 'Portugal',
       'Latvia', 'Philippines', 'Somaliland region', 'Morocco',
       'Macedonia', 'Mozambique', 'Albania', 'Bosnia and Herzegovina',
       'Lesotho', 'Dominican Republic', 'Laos', 'Mongolia', 'Swaziland',
       'Greece', 'Lebanon', 'Hungary', 'Honduras', 'Tajikistan',
       'Tunisia', 'Palestinian Territories', 'Bangladesh', 'Iran',
       'Ukraine', 'Iraq', 'South Africa', 'Ghana', 'Zimbabwe', 'Liberia',
       'India', 'Sudan', 'Haiti', 'Congo (Kinshasa)', 'Nepal', 'Ethiopia',
       'Sierra Leone', 'Mauritania', 'Kenya', 'Djibouti', 'Armenia',
       'Botswana', 'Myanmar', 'Georgia', 'Malawi', 'Sri Lanka',
       'Cameroon', 'Bulgaria', 'Egypt', 'Yemen', 'Angola', 'Mali',
       'Congo (Brazzaville)', 'Comoros', 'Uganda', 'Senegal', 'Gabon',
       'Niger', 'Cambodia', 'Tanzania', 'Madagascar',
       'Central African Republic', 'Chad', 'Guinea', 'Ivory Coast',
       'Burkina Faso', 'Afghanistan', 'Rwanda', 'Benin', 'Syria',
       'Burundi', 'Togo'], dtype=object)

In [4]:
cols_2015 = len(df_2015.axes[1])

In [5]:
cols_2015

12

In [6]:
rows_2015 = len(df_2015.axes[0])

In [7]:
rows_2015

158

In [8]:
df_2015.isna().sum()

Country                          0
Region                           0
Happiness Rank                   0
Happiness Score                  0
Standard Error                   0
Economy (GDP per Capita)         0
Family                           0
Health (Life Expectancy)         0
Freedom                          0
Trust (Government Corruption)    0
Generosity                       0
Dystopia Residual                0
dtype: int64

In [9]:
df_2019 = pd.read_csv("../original_data/2019.csv")

In [10]:
df_2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [11]:
df_2019.isna().sum()

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [12]:
cols_2019 = len(df_2019.axes[1])

In [13]:
cols_2019

9

In [14]:
rows_2019 = len(df_2019.axes[0])

In [15]:
rows_2019

156

In [16]:
df_2019['Country or region'].unique()

array(['Finland', 'Denmark', 'Norway', 'Iceland', 'Netherlands',
       'Switzerland', 'Sweden', 'New Zealand', 'Canada', 'Austria',
       'Australia', 'Costa Rica', 'Israel', 'Luxembourg',
       'United Kingdom', 'Ireland', 'Germany', 'Belgium', 'United States',
       'Czech Republic', 'United Arab Emirates', 'Malta', 'Mexico',
       'France', 'Taiwan', 'Chile', 'Guatemala', 'Saudi Arabia', 'Qatar',
       'Spain', 'Panama', 'Brazil', 'Uruguay', 'Singapore', 'El Salvador',
       'Italy', 'Bahrain', 'Slovakia', 'Trinidad & Tobago', 'Poland',
       'Uzbekistan', 'Lithuania', 'Colombia', 'Slovenia', 'Nicaragua',
       'Kosovo', 'Argentina', 'Romania', 'Cyprus', 'Ecuador', 'Kuwait',
       'Thailand', 'Latvia', 'South Korea', 'Estonia', 'Jamaica',
       'Mauritius', 'Japan', 'Honduras', 'Kazakhstan', 'Bolivia',
       'Hungary', 'Paraguay', 'Northern Cyprus', 'Peru', 'Portugal',
       'Pakistan', 'Russia', 'Philippines', 'Serbia', 'Moldova', 'Libya',
       'Montenegro', 'Tajikistan', 'Croatia', 'Hong Kong',
       'Dominican Republic', 'Bosnia and Herzegovina', 'Turkey',
       'Malaysia', 'Belarus', 'Greece', 'Mongolia', 'North Macedonia',
       'Nigeria', 'Kyrgyzstan', 'Turkmenistan', 'Algeria', 'Morocco',
       'Azerbaijan', 'Lebanon', 'Indonesia', 'China', 'Vietnam', 'Bhutan',
       'Cameroon', 'Bulgaria', 'Ghana', 'Ivory Coast', 'Nepal', 'Jordan',
       'Benin', 'Congo (Brazzaville)', 'Gabon', 'Laos', 'South Africa',
       'Albania', 'Venezuela', 'Cambodia', 'Palestinian Territories',
       'Senegal', 'Somalia', 'Namibia', 'Niger', 'Burkina Faso',
       'Armenia', 'Iran', 'Guinea', 'Georgia', 'Gambia', 'Kenya',
       'Mauritania', 'Mozambique', 'Tunisia', 'Bangladesh', 'Iraq',
       'Congo (Kinshasa)', 'Mali', 'Sierra Leone', 'Sri Lanka', 'Myanmar',
       'Chad', 'Ukraine', 'Ethiopia', 'Swaziland', 'Uganda', 'Egypt',
       'Zambia', 'Togo', 'India', 'Liberia', 'Comoros', 'Madagascar',
       'Lesotho', 'Burundi', 'Zimbabwe', 'Haiti', 'Botswana', 'Syria',
       'Malawi', 'Yemen', 'Rwanda', 'Tanzania', 'Afghanistan',
       'Central African Republic', 'South Sudan'], dtype=object)

In [17]:
countries_to_keep = ['Switzerland', 'Iceland', 'Denmark', 'Norway', 'Canada', 'Finland', 'Netherlands', 
                     'Sweden', 'New Zealand', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'Mexico', 
                     'United States', 'Brazil', 'Luxembourg', 'Ireland', 'Belgium', 'United Arab Emirates', 
                     'United Kingdom', 'Oman', 'Venezuela', 'Singapore', 'Panama', 'Germany', 'Chile', 'Qatar', 
                     'France', 'Argentina', 'Czech Republic', 'Uruguay', 'Colombia', 'Thailand', 'Saudi Arabia', 
                     'Spain', 'Malta', 'Taiwan', 'Kuwait', 'Slovakia', 'Japan', 'South Korea', 'Ecuador', 
                     'Bahrain', 'Italy', 'Bolivia', 'Moldova', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Lithuania', 
                     'Nicaragua', 'Peru', 'Belarus', 'Poland', 'Croatia', 'Libya', 'Russia', 'Jamaica', 'Cyprus', 
                     'Kosovo', 'Mauritius', 'Hong Kong', 'Estonia', 'Indonesia', 'Vietnam', 'Turkey', 'Kyrgyzstan', 
                     'Nigeria', 'Bhutan', 'Azerbaijan', 'Pakistan', 'Jordan', 'Montenegro', 'China', 'Zambia', 
                     'Romania', 'Serbia', 'Portugal', 'Latvia', 'Philippines', 'Morocco', 'Macedonia', 
                     'Mozambique', 'Albania', 'Bosnia and Herzegovina', 'Lesotho', 'Dominican Republic', 'Laos', 
                     'Mongolia', 'Greece', 'Lebanon', 'Hungary', 'Honduras', 'Tajikistan', 'Tunisia', 
                     'Palestinian Territories', 'Bangladesh', 'Iran', 'Ukraine', 'Iraq', 'South Africa', 'Ghana', 
                     'Zimbabwe', 'Liberia', 'India', 'Sudan', 'Haiti', 'Congo (Kinshasa)', 'Nepal', 'Ethiopia', 
                     'Sierra Leone', 'Mauritania', 'Kenya', 'Armenia', 'Botswana', 'Myanmar', 'Georgia', 'Malawi', 
                     'Sri Lanka', 'Cameroon', 'Bulgaria', 'Egypt', 'Yemen', 'Angola', 'Mali', 
                     'Congo (Brazzaville)', 'Comoros', 'Uganda', 'Senegal', 'Gabon', 'Niger', 'Cambodia', 
                     'Tanzania', 'Madagascar', 'Central African Republic', 'Chad', 'Guinea', 'Ivory Coast', 
                     'Burkina Faso', 'Afghanistan', 'Rwanda', 'Benin', 'Syria', 'Burundi', 'Togo']

filtered_df_2015 = df_2015[df_2015['Country'].isin(countries_to_keep)]

filtered_df_2019 = df_2019[df_2019['Country or region'].isin(countries_to_keep)]

In [18]:
clean_df_2015 = filtered_df_2015.rename(columns={'Country': 'country',
                                                 'Happiness Rank': 'happiness_rank', 
                                                 'Happiness Score': 'happiness_score',
                                                 'Economy (GDP per Capita)': 'gdp_per_capita',
                                                'Family': 'social_support', 
                                                 'Health (Life Expectancy)': 'life_expectancy',
                                                'Freedom': 'freedom', 
                                                'Trust (Government Corruption)': 'perception_of_corruption',
                                                'Generosity': 'generosity'})[['country', 'happiness_rank',
                                                                            'happiness_score', 'gdp_per_capita',
                                                                             'social_support', 'life_expectancy',
                                                                             'freedom', 'perception_of_corruption',
                                                                             'generosity']]

clean_df_2019 = filtered_df_2019.rename(columns={'Country or region': 'country', 'Overall rank': 'happiness_rank', 
                                                 'Score': 'happiness_score',
                                                'GDP per capita': 'gdp_per_capita',
                                                'Social support': 'social_support', 
                                                 'Healthy life expectancy': 'life_expectancy',
                                                'Freedom to make life choices': 'freedom', 
                                                'Perceptions of corruption': 'perception_of_corruption',
                                                'Generosity': 'generosity'})[['country', 'happiness_rank',
                                                                            'happiness_score', 'gdp_per_capita',
                                                                             'social_support', 'life_expectancy',
                                                                             'freedom', 'perception_of_corruption',
                                                                             'generosity']]

In [20]:
clean_df_2015

,country,happiness_rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,perception_of_corruption,generosity
0,Switzerland,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678
1,Iceland,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
2,Denmark,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
3,Norway,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
4,Canada,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811
...,...,...,...,...,...,...,...,...,...
153,Rwanda,154,3.465,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628
154,Benin,155,3.340,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260
155,Syria,156,3.006,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179
156,Burundi,157,2.905,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727
157,Togo,158,2.839,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681

In [21]:
clean_df_2019

,country,happiness_rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,perception_of_corruption,generosity
0,Finland,1,7.769,1.340,1.587,0.986,0.596,0.393,0.153
1,Denmark,2,7.600,1.383,1.573,0.996,0.592,0.410,0.252
2,Norway,3,7.554,1.488,1.582,1.028,0.603,0.341,0.271
3,Iceland,4,7.494,1.380,1.624,1.026,0.591,0.118,0.354
4,Netherlands,5,7.488,1.396,1.522,0.999,0.557,0.298,0.322
...,...,...,...,...,...,...,...,...,...
150,Yemen,151,3.380,0.287,1.163,0.463,0.143,0.077,0.108
151,Rwanda,152,3.334,0.359,0.711,0.614,0.555,0.411,0.217
152,Tanzania,153,3.231,0.476,0.885,0.499,0.417,0.147,0.276
153,Afghanistan,154,3.203,0.350,0.517,0.361,0.000,0.025,0.158
154,Central African Republic,155,3.083,0.026,0.000,0.105,0.225,0.035,0.235

In [22]:
clean_df_2015.to_csv("../cleaned_data/New_data_2015.csv")
clean_df_2019.to_csv("../cleaned_data/New_data_2019.csv")